#!/usr/bin/env python3
"""Build a self-contained GitHub Pages report from the Beehive archive.

Reads harness-archive/*.ndjson (whatever the archiver committed) and writes
site/index.html — one static, dependency-free page a participant can browse on
their own GitHub Pages: per-run summary (frames, alerts, errors, latency,
status), expandable per-frame smoke scores, and any tracebacks. No servers, no
external assets (Pages-CSP safe). Usage: build_report.py <archive_dir> <out_dir>
"""
import html
import json
import statistics
import sys
from pathlib import Path

ARCHIVE = Path(sys.argv[1] if len(sys.argv) > 1 else "harness-archive")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else "site")


def load_rows():
    for p in sorted(ARCHIVE.glob("*.ndjson")):
        for line in p.read_text(errors="replace").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue


def main() -> int:
    runs = {}
    for r in load_rows():
        m = r.get("meta") or {}
        rid = m.get("run_id") or f"{m.get('vsn','?')}/{m.get('task', m.get('job','job'))}"
        d = runs.setdefault(rid, {"scores": [], "lat": [], "alerts": 0,
                                  "errs": 0, "exit": None, "vsn": m.get("vsn", "?"),
                                  "last": r.get("timestamp", ""), "tb": []})
        n, v = r.get("name", ""), r.get("value")
        d["last"] = max(d["last"], r.get("timestamp", ""))
        if n == "detect.smoke_score":
            d["scores"].append((m.get("event", ""), m.get("frame", ""), v))
        elif n == "detect.alert" and v:
            d["alerts"] += 1
        elif n == "inference_ns":
            d["lat"].append(float(v) / 1e6)
        elif n == "harness.traceback":
            d["errs"] += 1
            d["tb"].append(f"{m.get('event','')} f{m.get('frame','')}: {str(v).strip().splitlines()[-1]}")
        elif n == "run.exit":
            d["exit"] = m.get("status")

    rows_html = []
    for rid, d in sorted(runs.items(), key=lambda kv: kv[1]["last"], reverse=True):
        med = f"{statistics.median(d['lat']):.1f}ms" if d["lat"] else "—"
        peak = f"{max(v for *_, v in d['scores']):.3f}" if d["scores"] else "—"
        badge = {"clean": "#15803d", "with-errors": "#b45309",
                 "killed": "#b91c1c"}.get(d["exit"], "#666")
        frames = "".join(
            f"<tr><td>{html.escape(str(e)[:20])}</td><td>{html.escape(str(f))}</td>"
            f"<td>{v:.3f}</td></tr>" for e, f, v in d["scores"][:200])
        tb = "".join(f"<div class=tb>{html.escape(t)}</div>" for t in d["tb"])
        rows_html.append(f"""<details><summary>
          <b>{html.escape(rid)}</b> <span class=vsn>{html.escape(d['vsn'])}</span>
          <span class=st style="color:{badge}">{d['exit'] or '?'}</span>
          · frames {len(d['scores'])} · alerts {d['alerts']} · err {d['errs']}
          · peak {peak} · med {med} · {html.escape(d['last'][:19])}</summary>
          {'<div class=tbs>'+tb+'</div>' if tb else ''}
          <table><tr><th>event</th><th>#</th><th>smoke</th></tr>{frames}</table>
        </details>""")

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "index.html").write_text(f"""<!doctype html><meta charset=utf-8>
<title>Smoke-harness runs</title><meta name=viewport content="width=device-width,initial-scale=1">
<style>body{{font:14px/1.5 system-ui,sans-serif;margin:1.2rem;max-width:60rem}}
h1{{font-size:1.3rem}}details{{border:1px solid #ddd;border-radius:6px;padding:.5rem .7rem;margin:.5rem 0}}
summary{{cursor:pointer}}.vsn{{color:#268;background:#eef4f8;border-radius:8px;padding:0 6px;font-size:12px}}
.st{{font-weight:600}}table{{border-collapse:collapse;width:100%;margin-top:.5rem;font-size:12.5px}}
td,th{{border-bottom:1px solid #eee;padding:2px 6px;text-align:left}}.tbs{{margin:.4rem 0}}
.tb{{font:12px ui-monospace,monospace;color:#b91c1c;background:#fef2f2;padding:3px 6px;border-radius:4px;margin:2px 0}}
.hd{{color:#555}}</style>
<h1>Smoke-harness runs <span class=hd>· {len(runs)} runs · from Beehive</span></h1>
<p class=hd>Auto-built from the committed Beehive archive. Each run is crash-safe
data the Sage node published; this page is generated by GitHub Actions — no live
server. candidate &ne; truth: these are detector outputs, not confirmed labels.</p>
{''.join(rows_html) or '<p>No runs archived yet — the archiver Action populates this on its schedule.</p>'}
""")
    print(f"report: {len(runs)} runs -> {OUT/'index.html'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
